import javax.swing.JFrame;
import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bijoy
 */
public class SaleForm extends javax.swing.JFrame {

    /**
     * Creates new form SaleForm
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public SaleForm() {
        initComponents();
        getArtList();
        getExbID();
    }
    
    public static String setArtIdentity(){
        
        return Art_Var;
    }
    public static String setCusName(){
        return Cus_Var;
    }
    public static String setExbID(){
        return Exb_ID;
    }
    public static String setPrice(){
        return at_price;
    }
    public void getArtList()
    {
        String listItem;
        listItem = "SELECT Art_ID,Art_Image FROM dartgallerydatabase.art WHERE Art_Status='Unsold' ";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(listItem);
            while(rs.next())
            {
                jComboBoxAID.addItem(rs.getString("Art_ID"));
                
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    public void getExbID()
    {
        String queryId="SELECT * FROM dartgallerydatabase.exhibition order by Exhibition_ID desc LIMIT 1";
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(queryId);
            if(rs.next())
            {
                jTextFieldExbID.setText(rs.getString("Exhibition_ID"));
              
            }

        } catch (SQLException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelAR1 = new javax.swing.JPanel();
        jLabelArt = new javax.swing.JLabel();
        jPanelAR2 = new javax.swing.JPanel();
        jLabelArtist = new javax.swing.JLabel();
        jPanelAR3 = new javax.swing.JPanel();
        jLabelExb = new javax.swing.JLabel();
        jPanelAR4 = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jPanelAR5 = new javax.swing.JPanel();
        jLabelAbout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSave = new javax.swing.JLabel();
        jLabelCancel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldExbID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButtonCard = new javax.swing.JRadioButton();
        jRadioButtonCash = new javax.swing.JRadioButton();
        jRadioButtonCheque = new javax.swing.JRadioButton();
        jTextFieldContact = new javax.swing.JTextField();
        jComboBoxAID = new javax.swing.JComboBox<>();
        jTextFieldCus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jLabelPrint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(4, 147, 114));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bijoy\\Downloads\\minus.png")); // NOI18N
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 1187, 14, 0);
        jPanel1.add(jLabelMin, gridBagConstraints);

        jLabelClose1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose1.setForeground(new java.awt.Color(255, 51, 51));
        jLabelClose1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bijoy\\Downloads\\cancel.png")); // NOI18N
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 14, 14, 34);
        jPanel1.add(jLabelClose1, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money.png"))); // NOI18N
        jLabel2.setText("SALE ART");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 830));

        jPanelAR1.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseExited(evt);
            }
        });

        jLabelArt.setBackground(new java.awt.Color(255, 255, 204));
        jLabelArt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelArt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR1Layout = new javax.swing.GroupLayout(jPanelAR1);
        jPanelAR1.setLayout(jPanelAR1Layout);
        jPanelAR1Layout.setHorizontalGroup(
            jPanelAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelArt)
                .addGap(19, 19, 19))
        );
        jPanelAR1Layout.setVerticalGroup(
            jPanelAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR2.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseExited(evt);
            }
        });

        jLabelArtist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelArtist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designer-artist.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR2Layout = new javax.swing.GroupLayout(jPanelAR2);
        jPanelAR2.setLayout(jPanelAR2Layout);
        jPanelAR2Layout.setHorizontalGroup(
            jPanelAR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelArtist)
                .addGap(19, 19, 19))
        );
        jPanelAR2Layout.setVerticalGroup(
            jPanelAR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelArtist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR3.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR3MouseExited(evt);
            }
        });

        jLabelExb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelExb.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR3Layout = new javax.swing.GroupLayout(jPanelAR3);
        jPanelAR3.setLayout(jPanelAR3Layout);
        jPanelAR3Layout.setHorizontalGroup(
            jPanelAR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelExb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelAR3Layout.setVerticalGroup(
            jPanelAR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR4.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR4MouseExited(evt);
            }
        });

        jLabelSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSearch.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR4Layout = new javax.swing.GroupLayout(jPanelAR4);
        jPanelAR4.setLayout(jPanelAR4Layout);
        jPanelAR4Layout.setHorizontalGroup(
            jPanelAR4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanelAR4Layout.setVerticalGroup(
            jPanelAR4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR5.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseExited(evt);
            }
        });

        jLabelAbout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAbout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR5Layout = new javax.swing.GroupLayout(jPanelAR5);
        jPanelAR5.setLayout(jPanelAR5Layout);
        jPanelAR5Layout.setHorizontalGroup(
            jPanelAR5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAbout)
                .addGap(19, 19, 19))
        );
        jPanelAR5Layout.setVerticalGroup(
            jPanelAR5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/browser (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanelAR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanelAR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanelAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanelAR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanelAR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(17, 34, 34));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSACTION INFORMATION");
        jLabel1.setOpaque(true);
        jPanel8.add(jLabel1);
        jLabel1.setBounds(0, 40, 1320, 40);

        jLabelSave.setBackground(new java.awt.Color(1, 50, 67));
        jLabelSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSave.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSave.setText("SAVE");
        jLabelSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSave.setOpaque(true);
        jLabelSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSaveMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelSave);
        jLabelSave.setBounds(530, 660, 250, 30);

        jLabelCancel.setBackground(new java.awt.Color(253, 87, 51));
        jLabelCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancel.setText("CANCEL SALE");
        jLabelCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCancel.setOpaque(true);
        jLabelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelCancel);
        jLabelCancel.setBounds(60, 660, 250, 30);

        jPanel4.setBackground(new java.awt.Color(92, 151, 191));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldExbID.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldExbID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldExbID.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CUSTOMER NAME                                      :   ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ART   ID                                                       :   ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MODE OF PAYMENT                                  :   ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CONTACT DETAIL                                      :   ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("EXHIBITION ID                                         :   ");

        buttonGroup1.add(jRadioButtonCard);
        jRadioButtonCard.setText("CARD");
        jRadioButtonCard.setOpaque(false);
        jRadioButtonCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCardActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCash);
        jRadioButtonCash.setText("CASH");
        jRadioButtonCash.setOpaque(false);
        jRadioButtonCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCashActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCheque);
        jRadioButtonCheque.setText("CHEQUE");
        jRadioButtonCheque.setOpaque(false);
        jRadioButtonCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonChequeActionPerformed(evt);
            }
        });

        jTextFieldContact.setBackground(new java.awt.Color(204, 204, 255));

        jComboBoxAID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Art ID" }));

        jTextFieldCus.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("*");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("*");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("*");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("*");

        jLabelError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jComboBoxAID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldExbID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jTextFieldCus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jRadioButtonCash, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButtonCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButtonCard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldExbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCash)
                            .addComponent(jRadioButtonCheque)
                            .addComponent(jRadioButtonCard)))))
        );

        jPanel8.add(jPanel4);
        jPanel4.setBounds(20, 120, 1260, 490);

        jLabelPrint.setBackground(new java.awt.Color(149, 165, 166));
        jLabelPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrint.setText("PRINT");
        jLabelPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPrint.setOpaque(true);
        jLabelPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPrintMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelPrint);
        jLabelPrint.setBounds(980, 660, 250, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jPanelAR1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseEntered
        jPanelAR1.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR1MouseEntered

    private void jPanelAR1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseExited
        jPanelAR1.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR1MouseExited

    private void jPanelAR2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseEntered
        jPanelAR2.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR2MouseEntered

    private void jPanelAR2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseExited
        jPanelAR2.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR2MouseExited

    private void jPanelAR3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR3MouseEntered
        jPanelAR3.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR3MouseEntered

    private void jPanelAR3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR3MouseExited
        jPanelAR3.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR3MouseExited

    private void jPanelAR4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR4MouseEntered
        jPanelAR4.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR4MouseEntered

    private void jPanelAR4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR4MouseExited
        jPanelAR4.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR4MouseExited

    private void jPanelAR5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseEntered
        jPanelAR5.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR5MouseEntered

    private void jPanelAR5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseExited
        jPanelAR5.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR5MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jRadioButtonChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonChequeActionPerformed
        paymentMode="Cheque";
    }//GEN-LAST:event_jRadioButtonChequeActionPerformed

    private void jRadioButtonCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCashActionPerformed
        paymentMode="Cash";
    }//GEN-LAST:event_jRadioButtonCashActionPerformed

    private void jPanelAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseClicked
        ArtRegForm arf = new ArtRegForm();
        arf.setVisible(true);
        arf.pack();
        arf.setLocationRelativeTo(null);
        arf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR1MouseClicked

    private void jPanelAR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseClicked
        ArtistRegForm atrf = new ArtistRegForm();
        atrf.setVisible(true);
        atrf.pack();
        atrf.setLocationRelativeTo(null);
        atrf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR2MouseClicked

    private void jPanelAR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR3MouseClicked
        UpdateForm uf = new UpdateForm();
        uf.setVisible(true);
        uf.pack();
        uf.setLocationRelativeTo(null);
        uf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR3MouseClicked

    private void jPanelAR4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR4MouseClicked
        ViewForm vf = new ViewForm();
        vf.setVisible(true);
        vf.pack();
        vf.setLocationRelativeTo(null);
        vf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR4MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanelAR5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseClicked
        OrganiseExbForm oef= new OrganiseExbForm();
        oef.setVisible(true);
        oef.pack();
        oef.setLocationRelativeTo(null);
        oef.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_jPanelAR5MouseClicked

    private void jRadioButtonCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCardActionPerformed
        paymentMode="Card";
    }//GEN-LAST:event_jRadioButtonCardActionPerformed

    private void jLabelSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSaveMouseClicked
       int flag=JOptionPane.showConfirmDialog(null, "FINAL CHANGES?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(flag==0)
        {
            String At_ID;
            int A_Price;
            String a_ID=jComboBoxAID.getSelectedItem().toString();
            String exb_ID=jTextFieldExbID.getText();
            String cus_Name=jTextFieldCus.getText();
            String cus_contact=jTextFieldContact.getText();
            String sale_payment=paymentMode;
            Art_Var=a_ID;
            Cus_Var=cus_Name;
            Exb_ID=exb_ID;
            
            if("".equals(a_ID) || "".equals(exb_ID) || "".equals(cus_Name) || "".equals(cus_contact) || "".equals(sale_payment))
            {
                jLabelError.setText("* Marked Fields Must Be Filled.");
            }
            else{
                String query="INSERT INTO `dartgallerydatabase`.`customer` (`Customer_Name`, `Customer_Contact`, `Exhibition_ID`,`Item_ID`,`mode_of_Payment`) VALUES ('"+cus_Name+"', '"+cus_contact+"','"+exb_ID+"','"+a_ID+"','"+sale_payment+"')";
                String update1="UPDATE  `dartgallerydatabase`.`art`  SET Art_Status ='Sold', Customer_ID='"+cus_Name+"', Sold_At='"+exb_ID+"' WHERE art.Art_ID = '"+ a_ID +"'";
                String update2="UPDATE  `dartgallerydatabase`.`exhibition`  SET Items_Sold =Items_Sold+1 WHERE exhibition.Exhibition_ID = '"+ exb_ID +"'";
                String retrieveQuery="SELECT Artist_ID,Art_Price FROM dartgallerydatabase.art WHERE Art_ID='"+a_ID+"'";


                try {
                    Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(retrieveQuery);
                    if(rs.next())
                    {

                        At_ID=rs.getString("Artist_ID");
                        A_Price=Integer.parseInt(rs.getString("Art_Price"));
                        at_price=rs.getString("Art_price");
                        String update3="UPDATE  `dartgallerydatabase`.`artist`  SET Art_Sold = Art_Sold + '1' , Artist_Earning=Artist_Earning+'"+A_Price+"' WHERE artist.Artist_ID = '"+ At_ID +"'";
                        st.executeUpdate(update3);
                    }

                    if(st.executeUpdate(query)>0 && st.executeUpdate(update1)>0 && st.executeUpdate(update2)>0)
                    {
                        jTextFieldExbID.setText("");
                        jTextFieldCus.setText("");
                        jTextFieldContact.setText("");                       
                        jComboBoxAID.setSelectedIndex(0);
                        jLabelError.setText("");
                        JOptionPane.showMessageDialog(null, "Item Sold");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        else
            JOptionPane.showMessageDialog(null, "Done");
    }//GEN-LAST:event_jLabelSaveMouseClicked

    private void jLabelPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrintMouseClicked
        SalePreview spf = new SalePreview();
        spf.setVisible(true);
        spf.pack();
        spf.setLocationRelativeTo(null);
        spf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabelPrintMouseClicked

    private void jLabelCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseClicked
        int flag=JOptionPane.showConfirmDialog(null, "Are You Sure?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if( flag==0){
            AdminDashboard ad = new AdminDashboard();
            ad.setVisible(true);
            ad.pack();
            ad.setLocationRelativeTo(null);
            ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jLabelCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleForm().setVisible(true);
            }
        });
    }
    private static String paymentMode;
    private static String Art_Var;
    private static String Cus_Var;
    private static String Exb_ID;
    private static String at_price;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxAID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelArt;
    private javax.swing.JLabel jLabelArtist;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelExb;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPrint;
    private javax.swing.JLabel jLabelSave;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelAR1;
    private javax.swing.JPanel jPanelAR2;
    private javax.swing.JPanel jPanelAR3;
    private javax.swing.JPanel jPanelAR4;
    private javax.swing.JPanel jPanelAR5;
    private javax.swing.JRadioButton jRadioButtonCard;
    private javax.swing.JRadioButton jRadioButtonCash;
    private javax.swing.JRadioButton jRadioButtonCheque;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldCus;
    private javax.swing.JTextField jTextFieldExbID;
    // End of variables declaration//GEN-END:variables
}
