
import javax.swing.JFrame;
import java.awt.Color;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFrame;
import java.sql.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bijoy
 */
public class UpdateForm extends javax.swing.JFrame {

    /**
     * Creates new form UpdateForm
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public UpdateForm() {
        initComponents();
        getItemArt();
        getArtistList();
        getExbList();
    }
    public void getArtistList()
    {
         String listItem="SELECT Artist_ID FROM dartgallerydatabase.artist ORDER BY Artist_ID";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(listItem);
            while(rs.next())
            {
                jComboBoxItemArtist.addItem(rs.getString("Artist_ID"));
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    public void getExbList()
    {
         String listItem="SELECT Exhibition_ID FROM dartgallerydatabase.exhibition ORDER BY Exhibition_ID";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(listItem);
            while(rs.next())
            {
                jComboBoxItemExb.addItem(rs.getString("Exhibition_ID"));
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    public void getItemArt()
    {
         String listItem="SELECT Art_ID FROM dartgallerydatabase.art ORDER BY Art_ID";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(listItem);
            while(rs.next())
            {
                jComboBoxItemArt.addItem(rs.getString("Art_ID"));
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupGender = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabelUpdate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelArt = new javax.swing.JPanel();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabelPhoto = new javax.swing.JLabel();
        jTextFieldAtID = new javax.swing.JTextField();
        jTextFieldAName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jDateChooserDate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldSoldAt = new javax.swing.JTextField();
        jLabelUpArt = new javax.swing.JLabel();
        jComboBoxItemArt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCus = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanelArtist = new javax.swing.JPanel();
        jTextFieldGender = new javax.swing.JTextField();
        jTextFieldAtCon = new javax.swing.JTextField();
        jTextFieldAtName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooserDOB = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxItemArtist = new javax.swing.JComboBox<>();
        jLabelUpArtist = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNation = new javax.swing.JTextField();
        jPanelExb = new javax.swing.JPanel();
        jTextFieldIncharge = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jDateChooserOrg = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVanue = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jComboBoxItemExb = new javax.swing.JComboBox<>();
        jLabelUpExb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAttendent = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldTotalArtsSold = new javax.swing.JTextField();
        jLabelED = new javax.swing.JLabel();
        jLabelArtD = new javax.swing.JLabel();
        jLabelAtD = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelAR1 = new javax.swing.JPanel();
        jLabelArt = new javax.swing.JLabel();
        jPanelAR2 = new javax.swing.JPanel();
        jLabelArtist = new javax.swing.JLabel();
        jPanelAR3 = new javax.swing.JPanel();
        jLabelExb = new javax.swing.JLabel();
        jPanelAR4 = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jPanelAR5 = new javax.swing.JPanel();
        jLabelAbout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabelUpdate.setBackground(new java.awt.Color(1, 50, 67));
        jLabelUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUpdate.setText("UPDATE");
        jLabelUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUpdate.setOpaque(true);
        jLabelUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelUpdate);
        jLabelUpdate.setBounds(740, 670, 320, 30);

        jLabel10.setBackground(new java.awt.Color(253, 87, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CANCEL");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel10);
        jLabel10.setBounds(260, 670, 320, 30);

        jLayeredPane1.setBackground(new java.awt.Color(204, 204, 255));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanelArt.setBackground(new java.awt.Color(108, 122, 137));
        jPanelArt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelArt.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldStatus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldStatus.setEnabled(false);

        jLabelPhoto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPhoto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo-camera (1).png"))); // NOI18N
        jLabelPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabelPhoto.setOpaque(true);

        jTextFieldAtID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAtID.setEnabled(false);
        jTextFieldAtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAtIDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  NAME OF ART                               :   ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("  ARTIST ID                                     :   ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("    DATE OF CREATION                     :   ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" PRICE                                              :");

        jDateChooserDate.setDateFormatString("yyyy-MM-dd");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("STATUS                                           :");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SOLD AT                                          :");

        jTextFieldSoldAt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSoldAt.setEnabled(false);

        jLabelUpArt.setBackground(new java.awt.Color(239, 72, 54));
        jLabelUpArt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUpArt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUpArt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUpArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        jLabelUpArt.setText("SEARCH  ");
        jLabelUpArt.setOpaque(true);
        jLabelUpArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpArtMouseClicked(evt);
            }
        });

        jComboBoxItemArt.setBackground(new java.awt.Color(149, 165, 166));
        jComboBoxItemArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxItemArt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Item" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("------------------------------------------------------------------------------------------------------Details---------------------------------------------------------------------------------------------");

        jTextFieldCus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCus.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PURCHASED BY                              :");

        javax.swing.GroupLayout jPanelArtLayout = new javax.swing.GroupLayout(jPanelArt);
        jPanelArt.setLayout(jPanelArtLayout);
        jPanelArtLayout.setHorizontalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jComboBoxItemArt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelUpArt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAtID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSoldAt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldCus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelArtLayout.setVerticalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxItemArt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpArt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addComponent(jTextFieldAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldAtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jDateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldSoldAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.add(jPanelArt, "card2");

        jPanelArtist.setBackground(new java.awt.Color(92, 151, 191));
        jPanelArtist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldGender.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldGender.setEnabled(false);

        jTextFieldAtCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAtConActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("   NAME OF ARTIST              :   ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("   CONTACT                            :   ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("   DATE OF BIRTH                 :   ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("    NATIONALITY                    :");

        jDateChooserDOB.setDateFormatString("yyyy-MM-dd");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("    GENDER                               :");

        jComboBoxItemArtist.setBackground(new java.awt.Color(149, 165, 166));
        jComboBoxItemArtist.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxItemArtist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Item" }));

        jLabelUpArtist.setBackground(new java.awt.Color(239, 72, 54));
        jLabelUpArtist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUpArtist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUpArtist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUpArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        jLabelUpArtist.setText("SEARCH  ");
        jLabelUpArtist.setOpaque(true);
        jLabelUpArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpArtistMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("------------------------------------------------------------------------------------------------------Details---------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout jPanelArtistLayout = new javax.swing.GroupLayout(jPanelArtist);
        jPanelArtist.setLayout(jPanelArtistLayout);
        jPanelArtistLayout.setHorizontalGroup(
            jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jComboBoxItemArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelUpArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextFieldAtName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldAtCon, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jDateChooserDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldNation, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelArtistLayout.setVerticalGroup(
            jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxItemArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAtCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelArtistLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jDateChooserDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.add(jPanelArtist, "card3");

        jPanelExb.setBackground(new java.awt.Color(242, 120, 75));
        jPanelExb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("       VENUE                                                    :   ");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("     DATE CREATED                                    :   ");

        jDateChooserOrg.setDateFormatString("yyyy-MM-dd");
        jDateChooserOrg.setEnabled(false);

        jTextAreaVanue.setColumns(20);
        jTextAreaVanue.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVanue);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("     PERSON INCHARGE                             :   ");

        jComboBoxItemExb.setBackground(new java.awt.Color(149, 165, 166));
        jComboBoxItemExb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxItemExb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Item" }));

        jLabelUpExb.setBackground(new java.awt.Color(4, 147, 114));
        jLabelUpExb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUpExb.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUpExb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUpExb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        jLabelUpExb.setText("SEARCH  ");
        jLabelUpExb.setOpaque(true);
        jLabelUpExb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpExbMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("------------------------------------------------------------------------------------------------------Details---------------------------------------------------------------------------------------------");

        jTextFieldAttendent.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("     TOTAL ATTENDENT                              :   ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("     TOTAL ARTS SOLD                               :   ");

        jTextFieldTotalArtsSold.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTotalArtsSold.setEnabled(false);

        javax.swing.GroupLayout jPanelExbLayout = new javax.swing.GroupLayout(jPanelExb);
        jPanelExb.setLayout(jPanelExbLayout);
        jPanelExbLayout.setHorizontalGroup(
            jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jComboBoxItemExb, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelUpExb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jDateChooserOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jTextFieldIncharge, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jTextFieldTotalArtsSold, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jTextFieldAttendent, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExbLayout.setVerticalGroup(
            jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxItemExb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpExb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExbLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelExbLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jDateChooserOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIncharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotalArtsSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAttendent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.add(jPanelExb, "card4");

        jPanel8.add(jLayeredPane1);
        jLayeredPane1.setBounds(30, 150, 1220, 450);

        jLabelED.setBackground(new java.awt.Color(242, 120, 75));
        jLabelED.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelED.setForeground(new java.awt.Color(255, 255, 255));
        jLabelED.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelED.setText("UDPATE EXHIBITION DETAILS");
        jLabelED.setOpaque(true);
        jLabelED.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEDMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelED);
        jLabelED.setBounds(930, 10, 234, 100);

        jLabelArtD.setBackground(new java.awt.Color(108, 122, 137));
        jLabelArtD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelArtD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelArtD.setText("UDPATE ART DETAILS");
        jLabelArtD.setOpaque(true);
        jLabelArtD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArtDMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelArtD);
        jLabelArtD.setBounds(180, 10, 234, 100);

        jLabelAtD.setBackground(new java.awt.Color(92, 151, 191));
        jLabelAtD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAtD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAtD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtD.setText("UDPATE ARTIST DETAILS");
        jLabelAtD.setOpaque(true);
        jLabelAtD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAtDMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelAtD);
        jLabelAtD.setBounds(550, 10, 234, 100);

        jPanel1.setBackground(new java.awt.Color(4, 147, 114));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bijoy\\Downloads\\minus.png")); // NOI18N
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 1093, 14, 0);
        jPanel1.add(jLabelMin, gridBagConstraints);

        jLabelClose1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose1.setForeground(new java.awt.Color(255, 51, 51));
        jLabelClose1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bijoy\\Downloads\\cancel.png")); // NOI18N
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 14, 14, 34);
        jPanel1.add(jLabelClose1, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        jLabel2.setText("Update Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 830));

        jPanelAR1.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseExited(evt);
            }
        });

        jLabelArt.setBackground(new java.awt.Color(255, 255, 204));
        jLabelArt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelArt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR1Layout = new javax.swing.GroupLayout(jPanelAR1);
        jPanelAR1.setLayout(jPanelAR1Layout);
        jPanelAR1Layout.setHorizontalGroup(
            jPanelAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelArt)
                .addGap(19, 19, 19))
        );
        jPanelAR1Layout.setVerticalGroup(
            jPanelAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR2.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseExited(evt);
            }
        });

        jLabelArtist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelArtist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designer-artist.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR2Layout = new javax.swing.GroupLayout(jPanelAR2);
        jPanelAR2.setLayout(jPanelAR2Layout);
        jPanelAR2Layout.setHorizontalGroup(
            jPanelAR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelArtist)
                .addGap(19, 19, 19))
        );
        jPanelAR2Layout.setVerticalGroup(
            jPanelAR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelArtist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR3.setBackground(new java.awt.Color(239, 72, 54));

        jLabelExb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelExb.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR3Layout = new javax.swing.GroupLayout(jPanelAR3);
        jPanelAR3.setLayout(jPanelAR3Layout);
        jPanelAR3Layout.setHorizontalGroup(
            jPanelAR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelExb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelAR3Layout.setVerticalGroup(
            jPanelAR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR4.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR4MouseExited(evt);
            }
        });

        jLabelSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSearch.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR4Layout = new javax.swing.GroupLayout(jPanelAR4);
        jPanelAR4.setLayout(jPanelAR4Layout);
        jPanelAR4Layout.setHorizontalGroup(
            jPanelAR4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanelAR4Layout.setVerticalGroup(
            jPanelAR4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR5.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseExited(evt);
            }
        });

        jLabelAbout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAbout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR5Layout = new javax.swing.GroupLayout(jPanelAR5);
        jPanelAR5.setLayout(jPanelAR5Layout);
        jPanelAR5Layout.setHorizontalGroup(
            jPanelAR5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAbout)
                .addGap(19, 19, 19))
        );
        jPanelAR5Layout.setVerticalGroup(
            jPanelAR5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(52, 73, 94));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/browser (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanelAR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanelAR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanelAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanelAR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanelAR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jPanelAR1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseEntered
        jPanelAR1.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR1MouseEntered

    private void jPanelAR1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseExited
        jPanelAR1.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR1MouseExited

    private void jPanelAR2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseEntered
        jPanelAR2.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR2MouseEntered

    private void jPanelAR2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseExited
        jPanelAR2.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR2MouseExited

    private void jPanelAR4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR4MouseEntered
        jPanelAR4.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR4MouseEntered

    private void jPanelAR4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR4MouseExited
        jPanelAR4.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR4MouseExited

    private void jPanelAR5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseEntered
        jPanelAR5.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR5MouseEntered

    private void jPanelAR5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseExited
        jPanelAR5.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR5MouseExited

    private void jTextFieldAtConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAtConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAtConActionPerformed

    private void jLabelArtDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArtDMouseClicked
        selectedBlock="ArtBlock";
        jPanelArt.setVisible(true);
        jPanelArtist.setVisible(false);
        jPanelExb.setVisible(false);
    }//GEN-LAST:event_jLabelArtDMouseClicked

    private void jLabelAtDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAtDMouseClicked
        selectedBlock="ArtistBlock";
        jPanelArtist.setVisible(true);
        jPanelArt.setVisible(false);
        jPanelExb.setVisible(false);
    }//GEN-LAST:event_jLabelAtDMouseClicked

    private void jLabelEDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEDMouseClicked
        selectedBlock="ExbBlock";
        jPanelExb.setVisible(true);
        jPanelArt.setVisible(false);
        jPanelArtist.setVisible(false);
    }//GEN-LAST:event_jLabelEDMouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanelAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseClicked
        ArtRegForm arf = new ArtRegForm();
        arf.setVisible(true);
        arf.pack();
        arf.setLocationRelativeTo(null);
        arf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR1MouseClicked

    private void jPanelAR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseClicked
        ArtistRegForm atrf = new ArtistRegForm();
        atrf.setVisible(true);
        atrf.pack();
        atrf.setLocationRelativeTo(null);
        atrf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR2MouseClicked

    private void jPanelAR4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR4MouseClicked
        ViewForm vf = new ViewForm();
        vf.setVisible(true);
        vf.pack();
        vf.setLocationRelativeTo(null);
        vf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR4MouseClicked

    private void jPanelAR5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseClicked
        OrganiseExbForm oef= new OrganiseExbForm();
        oef.setVisible(true);
        oef.pack();
        oef.setLocationRelativeTo(null);
        oef.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_jPanelAR5MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabelUpArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpArtMouseClicked
        ID=jComboBoxItemArt.getSelectedItem().toString();
        String retrieveQuery="SELECT * FROM dartgallerydatabase.art WHERE Art_ID='"+ID+"'";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(retrieveQuery);
            if(rs.next())
            {
                jTextFieldAName.setText(rs.getString("Art_Name"));
                jTextFieldAtID.setText(rs.getString("Artist_ID"));
                String dateValue = rs.getString("Date_Created");
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                jDateChooserDate.setDate(date);
                jTextFieldPrice.setText(rs.getString("Art_Price"));
                jTextFieldStatus.setText(rs.getString("Art_Status"));
                jTextFieldSoldAt.setText(rs.getString("Sold_At"));
                jTextFieldCus.setText(rs.getString("Customer_ID"));
                byte[] img=rs.getBytes("Art_Image");
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(jLabelPhoto.getWidth(), jLabelPhoto.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                jLabelPhoto.setIcon(newImage);

            }
        }catch(SQLException e){
            System.out.println(e);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelUpArtMouseClicked

    private void jTextFieldAtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAtIDActionPerformed

    private void jLabelUpArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpArtistMouseClicked
        ID=jComboBoxItemArtist.getSelectedItem().toString();
        String retrieveQuery="SELECT * FROM dartgallerydatabase.artist WHERE Artist_ID='"+ID+"'";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(retrieveQuery);
            if(rs.next())
            {
                jTextFieldAtName.setText(rs.getString("Artist_Name"));
                jTextFieldAtCon.setText(rs.getString("Artist_Contact"));
                String dateValue = rs.getString("Artist_DOB");
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                jDateChooserDOB.setDate(date);
                jTextFieldNation.setText(rs.getString("Artist_Nation"));
                jTextFieldGender.setText(rs.getString("Artist_Gender"));
                              
            }
        }catch(SQLException e){
            System.out.println(e);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateForm.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jLabelUpArtistMouseClicked
    
    private void jLabelUpExbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpExbMouseClicked
         ID=jComboBoxItemExb.getSelectedItem().toString();
        String retrieveQuery="SELECT * FROM dartgallerydatabase.exhibition WHERE Exhibition_ID='"+ID+"'";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(retrieveQuery);
            if(rs.next())
            {
                jTextAreaVanue.setText(rs.getString("Exhibition_Vanue"));
                jTextFieldIncharge.setText(rs.getString("Person_Incharge"));
                String dateValue = rs.getString("Date");
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                jDateChooserOrg.setDate(date);
                jTextFieldTotalArtsSold.setText(rs.getString("Items_Sold"));
                jTextFieldAttendent.setText(rs.getString("No_of_Attendent"));
                              
            }
        }catch(SQLException e){
            System.out.println(e);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jLabelUpExbMouseClicked

    private void jLabelUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateMouseClicked
        int flag=JOptionPane.showConfirmDialog(null, "FINAL CHANGES?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(flag==0)
        {
            if("ArtBlock".equals(selectedBlock))
            {
                String a_ID=jComboBoxItemArt.getSelectedItem().toString();
                String a_Name=jTextFieldAName.getText();
                java.util.Date dateOB= jDateChooserDate.getDate();
                SimpleDateFormat dateFor=new SimpleDateFormat("yyyy-MM-dd");
                String dateCreated= dateFor.format(dateOB);
                String at_price=jTextFieldPrice.getText();                
                String updateQuery="UPDATE  `dartgallerydatabase`.`art`  SET Art_Name =?, Art_Price=?, Date_Created=? WHERE art.Art_ID = '"+a_ID+"'";
                try {
                    Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
                    PreparedStatement pst=con.prepareStatement(updateQuery);
                    pst.setString(1, a_Name);
                    pst.setString(2,at_price);
                    pst.setString(3,dateCreated);
                    int status=pst.executeUpdate();
                    if(status>0)
                    {
                        JOptionPane.showMessageDialog(null, "Updated Successfully");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if("ArtistBlock".equals(selectedBlock))
            {
                String at_ID=jComboBoxItemArtist.getSelectedItem().toString();
                String at_Name=jTextFieldAtName.getText();
                String at_Con=jTextFieldAtCon.getText();
                java.util.Date dateOB= jDateChooserDOB.getDate();
                SimpleDateFormat dateFor=new SimpleDateFormat("yyyy-MM-dd");
                String dateDOB= dateFor.format(dateOB);
                String at_Nation=jTextFieldNation.getText();                
                String updateQuery="UPDATE  `dartgallerydatabase`.`artist`  SET Artist_Name ='"+at_Name+"', Artist_Contact='"+at_Con+"', Artist_DOB='"+dateDOB+"',Artist_Nation='"+at_Nation+"' WHERE artist.Artist_ID = '"+ at_ID +"'";
                try {
                    Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
                    Statement st=con.createStatement();
                    if(st.executeUpdate(updateQuery)>0)
                    {
                        JOptionPane.showMessageDialog(null, "Updated Successfully");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if("ExbBlock".equals(selectedBlock))
            {
                String exb_ID=jComboBoxItemExb.getSelectedItem().toString();
                String exb_Vanue=jTextAreaVanue.getText();
                String exb_Incharge=jTextFieldIncharge.getText();                
                String exb_artSold=jTextFieldTotalArtsSold.getText();
                String exb_Attendent=jTextFieldAttendent.getText();                
                String updateQuery="UPDATE  `dartgallerydatabase`.`exhibition`  SET Exhibition_Vanue ='"+exb_Vanue+"', Person_Incharge='"+exb_Incharge+"',Items_Sold='"+exb_artSold+"',No_of_Attendent='"+exb_Attendent+"' WHERE exhibition.Exhibition_ID = '"+ exb_ID +"'";
                try {
                    Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
                    Statement st=con.createStatement();
                    if(st.executeUpdate(updateQuery)>0)
                    {
                        JOptionPane.showMessageDialog(null, "Updated Successfully");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Done");
    }//GEN-LAST:event_jLabelUpdateMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        
        int flag=JOptionPane.showConfirmDialog(null, "Are You Sure?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if( flag==0){
            AdminDashboard ad = new AdminDashboard();
            ad.setVisible(true);
            ad.pack();
            ad.setLocationRelativeTo(null);
            ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateForm().setVisible(true);
            }
        });
    }
    
    private String ID;
    private String selectedBlock;
    private String filename=null;
    byte[] photo=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JComboBox<String> jComboBoxItemArt;
    private javax.swing.JComboBox<String> jComboBoxItemArtist;
    private javax.swing.JComboBox<String> jComboBoxItemExb;
    private com.toedter.calendar.JDateChooser jDateChooserDOB;
    private com.toedter.calendar.JDateChooser jDateChooserDate;
    private com.toedter.calendar.JDateChooser jDateChooserOrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelArt;
    private javax.swing.JLabel jLabelArtD;
    private javax.swing.JLabel jLabelArtist;
    private javax.swing.JLabel jLabelAtD;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelED;
    private javax.swing.JLabel jLabelExb;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelUpArt;
    private javax.swing.JLabel jLabelUpArtist;
    private javax.swing.JLabel jLabelUpExb;
    private javax.swing.JLabel jLabelUpdate;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelAR1;
    private javax.swing.JPanel jPanelAR2;
    private javax.swing.JPanel jPanelAR3;
    private javax.swing.JPanel jPanelAR4;
    private javax.swing.JPanel jPanelAR5;
    private javax.swing.JPanel jPanelArt;
    private javax.swing.JPanel jPanelArtist;
    private javax.swing.JPanel jPanelExb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVanue;
    private javax.swing.JTextField jTextFieldAName;
    private javax.swing.JTextField jTextFieldAtCon;
    private javax.swing.JTextField jTextFieldAtID;
    private javax.swing.JTextField jTextFieldAtName;
    private javax.swing.JTextField jTextFieldAttendent;
    private javax.swing.JTextField jTextFieldCus;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldIncharge;
    private javax.swing.JTextField jTextFieldNation;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldSoldAt;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTotalArtsSold;
    // End of variables declaration//GEN-END:variables
}
