
import javax.swing.JFrame;
import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import javax.swing.Icon;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.JOptionPane;
//import java.text.SimpleDateFormat;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bijoy
 */
public class ViewForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewForm
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ViewForm() {
        initComponents();
        getArtistList();
        getItemList();
        getExbList();
        
    }
    
    public void getArtistList()
    {
         String listItem="SELECT Artist_ID FROM dartgallerydatabase.artist ORDER BY Artist_ID";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(listItem);
            while(rs.next())
            {
                jComboBoxAtID.addItem(rs.getString("Artist_ID"));
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    public void getExbList()
    {
         String listItem="SELECT Exhibition_ID FROM dartgallerydatabase.exhibition ORDER BY Exhibition_ID";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(listItem);
            while(rs.next())
            {
                jComboBoxExbID.addItem(rs.getString("Exhibition_ID"));
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    public void getItemList()
    {
         String listItem="SELECT Art_ID FROM dartgallerydatabase.art ORDER BY Art_ID";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(listItem);
            while(rs.next())
            {
                jComboBoxItem.addItem(rs.getString("Art_ID"));
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelArt = new javax.swing.JPanel();
        jTextFieldCus = new javax.swing.JTextField();
        jLabelPhotoArt = new javax.swing.JLabel();
        jTextFieldDC = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jTextFieldSold = new javax.swing.JTextField();
        jTextFieldAtID = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jComboBoxItem = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelArtist = new javax.swing.JPanel();
        jTextFieldGender = new javax.swing.JTextField();
        jTextFieldDOB = new javax.swing.JTextField();
        jTextFieldArtist = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldContact = new javax.swing.JTextField();
        jTextFieldNation = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldArtSold = new javax.swing.JTextField();
        jTextFieldEarning = new javax.swing.JTextField();
        jLabelFindArtist = new javax.swing.JLabel();
        jComboBoxAtID = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanelExb = new javax.swing.JPanel();
        jTextFieldIncharge = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVanue = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldTotalArtsSold = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jComboBoxExbID = new javax.swing.JComboBox<>();
        jLabelFindExhibition = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAttendent = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabelED = new javax.swing.JLabel();
        jLabelArtD = new javax.swing.JLabel();
        jLabelAtD = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelAR1 = new javax.swing.JPanel();
        jLabelArt = new javax.swing.JLabel();
        jPanelAR2 = new javax.swing.JPanel();
        jLabelArtist = new javax.swing.JLabel();
        jPanelAR3 = new javax.swing.JPanel();
        jLabelExb = new javax.swing.JLabel();
        jPanelAR4 = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jPanelAR5 = new javax.swing.JPanel();
        jLabelAbout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(1, 50, 67));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DONE");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel8);
        jLabel8.setBounds(460, 680, 320, 30);

        jLayeredPane1.setBackground(new java.awt.Color(204, 204, 255));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanelArt.setBackground(new java.awt.Color(108, 122, 137));
        jPanelArt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelArt.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldCus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCus.setEnabled(false);

        jLabelPhotoArt.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPhotoArt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPhotoArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo-camera (1).png"))); // NOI18N
        jLabelPhotoArt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabelPhotoArt.setOpaque(true);

        jTextFieldDC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDC.setEnabled(false);
        jTextFieldDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDCActionPerformed(evt);
            }
        });

        jTextFieldName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldName.setEnabled(false);
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  NAME OF ART                               :   ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("  ARTIST ID                                     :   ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("    DATE OF CREATION                     :   ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("  PRICE                                             :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("  PURCHASED BY                             :");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("  STATUS                                          :");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("  SOLD AT                                         :");

        jTextFieldStatus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldStatus.setEnabled(false);

        jTextFieldSold.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSold.setEnabled(false);

        jTextFieldAtID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAtID.setEnabled(false);
        jTextFieldAtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAtIDActionPerformed(evt);
            }
        });

        jTextFieldPrice.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrice.setEnabled(false);

        jComboBoxItem.setBackground(new java.awt.Color(149, 165, 166));
        jComboBoxItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Item" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("------------------------------------------------------------------------------------------------------Details---------------------------------------------------------------------------------------------");

        jLabel4.setBackground(new java.awt.Color(239, 72, 54));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        jLabel4.setText("SEARCH  ");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelArtLayout = new javax.swing.GroupLayout(jPanelArt);
        jPanelArt.setLayout(jPanelArtLayout);
        jPanelArtLayout.setHorizontalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAtID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSold, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170)
                .addComponent(jLabelPhotoArt, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldCus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelArtLayout.setVerticalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPhotoArt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jTextFieldAtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jTextFieldDC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jTextFieldSold, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.add(jPanelArt, "card2");

        jPanelArtist.setBackground(new java.awt.Color(92, 151, 191));
        jPanelArtist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldGender.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldGender.setEnabled(false);

        jTextFieldDOB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDOB.setEnabled(false);
        jTextFieldDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDOBActionPerformed(evt);
            }
        });

        jTextFieldArtist.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldArtist.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("   NAME OF ARTIST              :   ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("   CONTACT                            :   ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("   DATE OF BIRTH                 :   ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("    NATIONALITY                    :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("    GENDER                               :");

        jTextFieldContact.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldContact.setEnabled(false);
        jTextFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactActionPerformed(evt);
            }
        });

        jTextFieldNation.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNation.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("    TOTAL EARNING                 :");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("    ARTS SOLD                          :");

        jTextFieldArtSold.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldArtSold.setEnabled(false);

        jTextFieldEarning.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEarning.setEnabled(false);

        jLabelFindArtist.setBackground(new java.awt.Color(239, 72, 54));
        jLabelFindArtist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFindArtist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFindArtist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFindArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        jLabelFindArtist.setText("SEARCH  ");
        jLabelFindArtist.setOpaque(true);
        jLabelFindArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFindArtistMouseClicked(evt);
            }
        });

        jComboBoxAtID.setBackground(new java.awt.Color(149, 165, 166));
        jComboBoxAtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxAtID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Item" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("------------------------------------------------------------------------------------------------------DETAILS---------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout jPanelArtistLayout = new javax.swing.GroupLayout(jPanelArtist);
        jPanelArtist.setLayout(jPanelArtistLayout);
        jPanelArtistLayout.setHorizontalGroup(
            jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jComboBoxAtID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelFindArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextFieldArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldNation, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldArtSold, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldEarning, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelArtistLayout.setVerticalGroup(
            jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtistLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFindArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(23, 23, 23)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldArtSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEarning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.add(jPanelArtist, "card3");

        jPanelExb.setBackground(new java.awt.Color(242, 120, 75));
        jPanelExb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldIncharge.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIncharge.setEnabled(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("       VANUE                                                    :   ");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("     DATE CREATED                                    :   ");

        jTextAreaVanue.setColumns(20);
        jTextAreaVanue.setRows(5);
        jTextAreaVanue.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaVanue.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaVanue);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("     PERSON INCHARGE                             :   ");

        jTextFieldDate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDate.setEnabled(false);

        jTextFieldTotalArtsSold.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTotalArtsSold.setEnabled(false);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("     TOTAL ARTS SOLD                               :   ");

        jComboBoxExbID.setBackground(new java.awt.Color(149, 165, 166));
        jComboBoxExbID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxExbID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Item" }));

        jLabelFindExhibition.setBackground(new java.awt.Color(4, 147, 114));
        jLabelFindExhibition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFindExhibition.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFindExhibition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFindExhibition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        jLabelFindExhibition.setText("SEARCH  ");
        jLabelFindExhibition.setOpaque(true);
        jLabelFindExhibition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFindExhibitionMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("------------------------------------------------------------------------------------------------------DETAILS---------------------------------------------------------------------------------------------");

        jTextFieldAttendent.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAttendent.setEnabled(false);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("     TOTAL ATTENDENT                              :   ");

        javax.swing.GroupLayout jPanelExbLayout = new javax.swing.GroupLayout(jPanelExb);
        jPanelExb.setLayout(jPanelExbLayout);
        jPanelExbLayout.setHorizontalGroup(
            jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jComboBoxExbID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelFindExhibition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jTextFieldIncharge, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jTextFieldTotalArtsSold, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jTextFieldAttendent, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExbLayout.setVerticalGroup(
            jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExbLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxExbID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFindExhibition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExbLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIncharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotalArtsSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelExbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAttendent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.add(jPanelExb, "card4");

        jPanel8.add(jLayeredPane1);
        jLayeredPane1.setBounds(30, 150, 1220, 450);

        jLabelED.setBackground(new java.awt.Color(242, 120, 75));
        jLabelED.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelED.setForeground(new java.awt.Color(255, 255, 255));
        jLabelED.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelED.setText("VIEW EXHIBITION DETAILS");
        jLabelED.setOpaque(true);
        jLabelED.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEDMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelED);
        jLabelED.setBounds(930, 10, 234, 100);

        jLabelArtD.setBackground(new java.awt.Color(108, 122, 137));
        jLabelArtD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelArtD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelArtD.setText("VIEW ART DETAILS");
        jLabelArtD.setOpaque(true);
        jLabelArtD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArtDMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelArtD);
        jLabelArtD.setBounds(180, 10, 234, 100);

        jLabelAtD.setBackground(new java.awt.Color(92, 151, 191));
        jLabelAtD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAtD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAtD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtD.setText("VIEW ARTIST DETAILS");
        jLabelAtD.setOpaque(true);
        jLabelAtD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAtDMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelAtD);
        jLabelAtD.setBounds(550, 10, 234, 100);

        jPanel1.setBackground(new java.awt.Color(4, 147, 114));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bijoy\\Downloads\\minus.png")); // NOI18N
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 1113, 14, 0);
        jPanel1.add(jLabelMin, gridBagConstraints);

        jLabelClose1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose1.setForeground(new java.awt.Color(255, 51, 51));
        jLabelClose1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bijoy\\Downloads\\cancel.png")); // NOI18N
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 14, 14, 34);
        jPanel1.add(jLabelClose1, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewtitle.png"))); // NOI18N
        jLabel2.setText("View Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 830));

        jPanelAR1.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR1MouseExited(evt);
            }
        });

        jLabelArt.setBackground(new java.awt.Color(255, 255, 204));
        jLabelArt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelArt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR1Layout = new javax.swing.GroupLayout(jPanelAR1);
        jPanelAR1.setLayout(jPanelAR1Layout);
        jPanelAR1Layout.setHorizontalGroup(
            jPanelAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelArt)
                .addGap(19, 19, 19))
        );
        jPanelAR1Layout.setVerticalGroup(
            jPanelAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR2.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR2MouseExited(evt);
            }
        });

        jLabelArtist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelArtist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designer-artist.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR2Layout = new javax.swing.GroupLayout(jPanelAR2);
        jPanelAR2.setLayout(jPanelAR2Layout);
        jPanelAR2Layout.setHorizontalGroup(
            jPanelAR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelArtist)
                .addGap(19, 19, 19))
        );
        jPanelAR2Layout.setVerticalGroup(
            jPanelAR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelArtist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR3.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR3MouseExited(evt);
            }
        });

        jLabelExb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelExb.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR3Layout = new javax.swing.GroupLayout(jPanelAR3);
        jPanelAR3.setLayout(jPanelAR3Layout);
        jPanelAR3Layout.setHorizontalGroup(
            jPanelAR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelExb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelAR3Layout.setVerticalGroup(
            jPanelAR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR4.setBackground(new java.awt.Color(239, 72, 54));

        jLabelSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSearch.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR4Layout = new javax.swing.GroupLayout(jPanelAR4);
        jPanelAR4.setLayout(jPanelAR4Layout);
        jPanelAR4Layout.setHorizontalGroup(
            jPanelAR4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanelAR4Layout.setVerticalGroup(
            jPanelAR4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAR5.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAR5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAR5MouseExited(evt);
            }
        });

        jLabelAbout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAbout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAR5Layout = new javax.swing.GroupLayout(jPanelAR5);
        jPanelAR5.setLayout(jPanelAR5Layout);
        jPanelAR5Layout.setHorizontalGroup(
            jPanelAR5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAR5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAbout)
                .addGap(19, 19, 19))
        );
        jPanelAR5Layout.setVerticalGroup(
            jPanelAR5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAR5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(52, 73, 94));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/browser (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAR5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanelAR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanelAR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanelAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanelAR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanelAR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDCActionPerformed

    private void jTextFieldDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOBActionPerformed

    private void jLabelEDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEDMouseClicked
        jPanelExb.setVisible(true);
        jPanelArt.setVisible(false);
        jPanelArtist.setVisible(false);
    }//GEN-LAST:event_jLabelEDMouseClicked

    private void jLabelArtDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArtDMouseClicked
        jPanelArt.setVisible(true);
        jPanelArtist.setVisible(false);
        jPanelExb.setVisible(false);
    }//GEN-LAST:event_jLabelArtDMouseClicked

    private void jLabelAtDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAtDMouseClicked
        jPanelArtist.setVisible(true);
        jPanelArt.setVisible(false);
        jPanelExb.setVisible(false);
    }//GEN-LAST:event_jLabelAtDMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jPanelAR1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseEntered
        jPanelAR1.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR1MouseEntered

    private void jPanelAR1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseExited
        jPanelAR1.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR1MouseExited

    private void jPanelAR2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseEntered
        jPanelAR2.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR2MouseEntered

    private void jPanelAR2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseExited
        jPanelAR2.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR2MouseExited

    private void jPanelAR3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR3MouseEntered
        jPanelAR3.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR3MouseEntered

    private void jPanelAR3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR3MouseExited
        jPanelAR3.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR3MouseExited

    private void jPanelAR5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseEntered
        jPanelAR5.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanelAR5MouseEntered

    private void jPanelAR5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseExited
        jPanelAR5.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanelAR5MouseExited

    private void jTextFieldAtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAtIDActionPerformed

    private void jTextFieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactActionPerformed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(Color.decode("#EF4836"));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(Color.decode("#34495E"));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanelAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR1MouseClicked
        ArtRegForm arf = new ArtRegForm();
        arf.setVisible(true);
        arf.pack();
        arf.setLocationRelativeTo(null);
        arf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR1MouseClicked

    private void jPanelAR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR2MouseClicked
        ArtistRegForm atrf = new ArtistRegForm();
        atrf.setVisible(true);
        atrf.pack();
        atrf.setLocationRelativeTo(null);
        atrf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR2MouseClicked

    private void jPanelAR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR3MouseClicked
        UpdateForm uf = new UpdateForm();
        uf.setVisible(true);
        uf.pack();
        uf.setLocationRelativeTo(null);
        uf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanelAR3MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        ID=jComboBoxItem.getSelectedItem().toString();
        String retrieveQuery="SELECT * FROM dartgallerydatabase.art WHERE Art_ID='"+ID+"'";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(retrieveQuery);
            if(rs.next())
            {
                jTextFieldName.setText(rs.getString("Art_Name"));
                jTextFieldAtID.setText(rs.getString("Artist_ID"));
                jTextFieldDC.setText(rs.getString("Date_Created"));
                jTextFieldPrice.setText(rs.getString("Art_Price"));
                jTextFieldStatus.setText(rs.getString("Art_Status"));
                jTextFieldSold.setText(rs.getString("Sold_At"));
                jTextFieldCus.setText(rs.getString("Customer_ID"));
                byte[] img=rs.getBytes("Art_Image");
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(jLabelPhotoArt.getWidth(), jLabelPhotoArt.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                jLabelPhotoArt.setIcon(newImage);
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabelFindArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFindArtistMouseClicked
        ID=jComboBoxAtID.getSelectedItem().toString();
        String retrieveQuery="SELECT * FROM dartgallerydatabase.artist WHERE Artist_ID='"+ID+"'";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(retrieveQuery);
            if(rs.next())
            {
                jTextFieldArtist.setText(rs.getString("Artist_Name"));
                jTextFieldContact.setText(rs.getString("Artist_Contact"));
                jTextFieldDOB.setText(rs.getString("Artist_DOB"));
                jTextFieldNation.setText(rs.getString("Artist_Nation"));
                jTextFieldGender.setText(rs.getString("Artist_Gender"));
                jTextFieldArtSold.setText(rs.getString("Art_Sold"));
                jTextFieldEarning.setText(rs.getString("Artist_Earning"));
                
                
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabelFindArtistMouseClicked

    private void jLabelFindExhibitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFindExhibitionMouseClicked
        ID=jComboBoxExbID.getSelectedItem().toString();
        String retrieveQuery="SELECT * FROM dartgallerydatabase.exhibition WHERE Exhibition_ID='"+ID+"'";
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dartgallerydatabase", "root", "pwd123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(retrieveQuery);
            if(rs.next())
            {
                jTextAreaVanue.setText(rs.getString("Exhibition_Vanue"));
                jTextFieldDate.setText(rs.getString("Date"));
                jTextFieldIncharge.setText(rs.getString("Person_Incharge"));
                jTextFieldTotalArtsSold.setText(rs.getString("Items_Sold"));
                jTextFieldAttendent.setText(rs.getString("No_of_Attendent"));
                
                
                
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabelFindExhibitionMouseClicked

    private void jPanelAR5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAR5MouseClicked
        OrganiseExbForm oef= new OrganiseExbForm();
        oef.setVisible(true);
        oef.pack();
        oef.setLocationRelativeTo(null);
        oef.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_jPanelAR5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int flag=JOptionPane.showConfirmDialog(null, "Are You Sure?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if( flag==0){
            AdminDashboard ad = new AdminDashboard();
            ad.setVisible(true);
            ad.pack();
            ad.setLocationRelativeTo(null);
            ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewForm().setVisible(true);
            }
        });
    }
    private String ID;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxAtID;
    private javax.swing.JComboBox<String> jComboBoxExbID;
    private javax.swing.JComboBox<String> jComboBoxItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelArt;
    private javax.swing.JLabel jLabelArtD;
    private javax.swing.JLabel jLabelArtist;
    private javax.swing.JLabel jLabelAtD;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelED;
    private javax.swing.JLabel jLabelExb;
    private javax.swing.JLabel jLabelFindArtist;
    private javax.swing.JLabel jLabelFindExhibition;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPhotoArt;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelAR1;
    private javax.swing.JPanel jPanelAR2;
    private javax.swing.JPanel jPanelAR3;
    private javax.swing.JPanel jPanelAR4;
    private javax.swing.JPanel jPanelAR5;
    private javax.swing.JPanel jPanelArt;
    private javax.swing.JPanel jPanelArtist;
    private javax.swing.JPanel jPanelExb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVanue;
    private javax.swing.JTextField jTextFieldArtSold;
    private javax.swing.JTextField jTextFieldArtist;
    private javax.swing.JTextField jTextFieldAtID;
    private javax.swing.JTextField jTextFieldAttendent;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldCus;
    private javax.swing.JTextField jTextFieldDC;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldEarning;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldIncharge;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNation;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldSold;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTotalArtsSold;
    // End of variables declaration//GEN-END:variables
}
